#!/bin/bash

DOCKERIMAGE=titpetric/netdata:1.11
IMAGE=$(basename ${PWD})
STORE=${STORE:-${HOME}/store/${IMAGE}}
SECRET=${SECRET:-${STORE}/.secret}

TGBOTTOKEN=`cat ${SECRET}/.netdata/tg-bot-token`
TGCHATID=`cat ${SECRET}/.netdata/tg-chatid`

case $1 in
	"secret")
		mkdir -p ${SECRET}/.netdata/
		read -p "[netdata] Input Telegram bot-token:" TG_BOT_TOKEN
		echo $TG_BOT_TOKEN > ${SECRET}/.netdata/tg-bot-token
		read -p "[netdata] Input Telegram chatid:" TG_CHATID
		echo $TG_CHATID > ${SECRET}/.netdata/tg-chatid
		;;
	"up")
		$0 down
		shift
		DOCKER_OPTIONS=$*
		# issue: found message 'apparmor="DENIED" operation="ptrace"' in kern.log.
		# ref: https://github.com/moby/moby/issues/7276
		docker run -d --cap-add SYS_PTRACE \
			--security-opt seccomp:unconfined --security-opt apparmor:unconfined \
			--restart=always \
			-v ${PWD}/netdata.conf:/etc/netdata/netdata.conf:ro \
			-v ${PWD}/httpcheck.conf:/etc/netdata/orig/health.d/httpcheck.conf:ro \
			-v /proc:/host/proc:ro \
			-v /sys:/host/sys:ro \
			-v /var/run/docker.sock:/var/run/docker.sock:ro \
			--network=host \
			-e TELEGRAM_BOT_TOKEN=${TGBOTTOKEN} \
                	-e TELEGRAM_CHAT_ID=${TGCHATID} \
			--name ${IMAGE} \
			${DOCKER_OPTIONS} \
			${DOCKERIMAGE}
		;;
	"down")
		$0 p-down
		docker stop ${IMAGE}
		docker rm ${IMAGE}
		;;
	"clean")
		$0 down
		docker rmi ${DOCKERIMAGE}
		;;
	"p-up")
		$0 p-down
		shift
		DOCKER_OPTIONS=$*
		sudo mkdir -p ${STORE}/`hostname`/prometheus
		sudo chown nobody:nogroup ${STORE}/`hostname`/prometheus
		docker run -d --name prometheus \
			--restart=always \
			--network=host \
			-v ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml \
			-v ${STORE}/`hostname`/prometheus:/prometheus \
			${DOCKER_OPTIONS} \
			prom/prometheus:v2.9.1
		;;
	"p-down")
		docker stop prometheus
		docker rm prometheus
		;;
	*)
		echo $(basename $0) secret
		echo $(basename $0) up ...
		echo $(basename $0) down
		echo $(basename $0) clean
		echo $(basename $0) p-up ...
		echo $(basename $0) p-down
		;;
esac
