#!/bin/bash

DOCKERIMAGE=titpetric/netdata:1.15.0
IMAGE=$(basename ${PWD})
STOREBASE=${STOREBASE:-${HOME}/store}
SECRET=${SECRET:-${STOREBASE}/.secret}
STORE=${STORE:-${STOREBASE}/${IMAGE}}

TGBOTTOKEN=${TGBOTTOKEN:-`cat ${SECRET}/.netdata/tg-bot-token`}
TGCHATID=${TGCHATID:-`cat ${SECRET}/.netdata/tg-chatid`}

case $1 in
	"secret")
		mkdir -p ${SECRET}/.netdata/
		read -p "[netdata] Input Telegram bot-token:" TG_BOT_TOKEN
		echo $TG_BOT_TOKEN > ${SECRET}/.netdata/tg-bot-token
		read -p "[netdata] Input Telegram chatid:" TG_CHATID
		echo $TG_CHATID > ${SECRET}/.netdata/tg-chatid
		;;
	"up")
		$0 down
		shift
		DOCKER_OPTIONS=$*
		# issue: found message 'apparmor="DENIED" operation="ptrace"' in kern.log.
		# ref: https://github.com/moby/moby/issues/7276
		docker run -d --cap-add SYS_PTRACE \
			--security-opt seccomp:unconfined --security-opt apparmor:unconfined \
			--restart=always \
			-v ${PWD}/netdata.conf:/etc/netdata/netdata.conf:ro \
			-v /proc:/host/proc:ro \
			-v /sys:/host/sys:ro \
			-v /var/run/docker.sock:/var/run/docker.sock:ro \
			--network=host \
			-e TELEGRAM_BOT_TOKEN=${TGBOTTOKEN} \
                	-e TELEGRAM_CHAT_ID=${TGCHATID} \
			--name ${IMAGE} \
			${DOCKER_OPTIONS} \
			${DOCKERIMAGE}
		;;
	"down")
		docker stop ${IMAGE}
		docker rm ${IMAGE}
		;;
	"clean")
		$0 down
		docker rmi ${DOCKERIMAGE}
		;;
	*)
		echo $(basename $0) secret
		echo $(basename $0) up ...
		echo $(basename $0) down
		echo $(basename $0) clean
		;;
esac
