#!/bin/bash

DOCKERIMAGE=mikesplain/openvas:9

case $1 in
	"up")
		docker run -d -p 443:443 --name openvas ${DOCKERIMAGE}
		;;
	"down")
		docker stop openvas
		;;
	"clean")
		docker rm openvas
		;;
	*)
		echo $(basename $0) up
		echo $(basename $0) down
		echo $(basename $0) clean
		;;
esac
