#!/bin/bash

IMAGE=$(basename ${PWD})
STOREBASE=${STOREBASE:-${HOME}/store}
SECRET=${SECRET:-${STOREBASE}/.secret}
STORE=${STORE:-${STOREBASE}/${IMAGE}}

case $1 in
	"up")
		$0 down
		shift
		DOCKER_OPTIONS=$*
		docker run -d --name=${IMAGE} \
			--restart=always \
			-v ${STORE}/apps:/var/www/html/apps \
			-v ${STORE}/config:/var/www/html/config \
			-v ${STORE}/data:/var/www/html/data \
			-v ${PWD}/htaccess:/var/www/html/.htaccess \
			-v ${PWD}/user.ini:/var/www/html/.user.ini \
			${DOCKER_OPTIONS} \
			${IMAGE}
		;;
	"down")
		docker stop ${IMAGE}
		docker rm ${IMAGE}
		;;
	"clean")
		$0 down
		docker rmi ${IMAGE}
		;;
	*)
		echo $(basename $0) up ...
		echo $(basename $0) down
		echo $(basename $0) clean
		;;
esac
