#!/bin/bash

IMAGE=$(basename ${PWD})
STOREBASE=${STOREBASE:-${HOME}/store}
SECRET=${SECRET:-${STOREBASE}/.secret}
STORE=${STORE:-${STOREBASE}/${IMAGE}}

case $1 in
	"build")
		docker build -t ${IMAGE} .
		;;
	"up")
		$0 down
		shift
		DOCKER_OPTIONS=$*
		docker run -d \
			--restart=always \
			--name ${IMAGE} \
			-v ${STORE}/var/opt/svn:/var/opt/svn \
			${DOCKER_OPTIONS} \
			${IMAGE}
		;;
	"down")
		docker stop ${IMAGE}
		docker rm ${IMAGE}
		;;
	"clean")
		$0 down
		docker rmi ${IMAGE}
		;;
	"cleanclean")
		$0 clean
		sudo rm -rf ${STORE}
		;;
	*)
		echo $(basename $0) build
		echo $(basename $0) up ...
		echo $(basename $0) down
		echo $(basename $0) clean
		echo $(basename $0) cleanclean
		;;
esac
