#!/bin/bash
# Copyright 2018 tarlety@gmail.com

IMAGE=$(basename ${PWD})
[ "${STORE}" == "" ] && STORE=${HOME}/store/${IMAGE} || STORE=${STORE}/${IMAGE}
CERTS=${HOME}/.secret/.certs/registry

case $1 in
	"certs")
		mkdir -p ${CERTS}
		openssl req \
			-newkey rsa:4096 -nodes -sha256 -keyout ${CERTS}/domain.key \
			-x509 -days 365 -out ${CERTS}/domain.crt
		;;
	"trust")
		openssl s_client -connect localhost:5000 -showcerts < /dev/null 2>/dev/null \
			| openssl x509 -outform PEM \
			| sudo tee /usr/local/share/ca-certificates/ubuntu.crt
		sudo update-ca-certificates
		sudo service docker restart
		;;
	"store")
		sudo rm -rf ${STORE}
		sudo mkdir -p ${STORE}/certs
		sudo cp ${CERTS}/* ${STORE}/certs
		sudo chown root:root ${STORE}/certs/*
		sudo chmod 400 ${STORE}/certs/*
		;;
	"up")
		$0 down
		shift
		DOCKER_OPTIONS=$*
		docker start ${IMAGE} || \
		docker run -d --name=${IMAGE} \
			--restart=always \
			-v ${STORE}/certs:/certs \
			-v ${STORE}:/var/lib/registry \
			-e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
			-e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
			${DOCKER_OPTIONS} \
			${IMAGE}
		;;
	"down")
		docker stop ${IMAGE}
		docker rm ${IMAGE}
		;;
	"clean")
		$0 down
		docker rmi ${DOCKERIMAGE}
		;;
	"ui")
		docker run -it -p 8080:8080 --rm \
			--link ${IMAGE} \
			-e REGISTRY_URL=https://${IMAGE}:5000/v2 \
			-e REGISTRY_TRUST_ANY_SSL=true \
			-e REGISTRY_NAME=localhost:5000 \
			hyper/docker-registry-web
		;;
	*)
		echo $(basename $0) certs
		echo $(basename $0) trust
		echo $(basename $0) up ...
		echo $(basename $0) down
		echo $(basename $0) clean
		echo $(basename $0) ui
		;;
esac
