#!/bin/bash

DOCKERIMAGE=ceph/daemon:v3.2.1-stable-3.2-luminous-debian-9-x86_64
CEPHCOMMON_VERSION='=12.2.13-0ubuntu0.18.04.2'
IMAGE=$(basename ${PWD})

case $1 in
	"mon")
		shift
		HOSTIP=$1
		NETWORK=$2
		docker run -d --net=host \
			--restart=always \
			-v /etc/ceph:/etc/ceph \
			-v /var/log/ceph/:/var/log/ceph/ \
			-v /var/lib/ceph/mon:/var/lib/ceph/mon \
			-v /var/lib/ceph/bootstrap-mds:/var/lib/ceph/bootstrap-mds \
			-v /var/lib/ceph/bootstrap-osd:/var/lib/ceph/bootstrap-osd \
			-v /var/lib/ceph/bootstrap-rbd:/var/lib/ceph/bootstrap-rbd \
			-v /var/lib/ceph/bootstrap-rgw:/var/lib/ceph/bootstrap-rgw \
			-e MON_IP=$HOSTIP \
			-e CEPH_PUBLIC_NETWORK=$NETWORK \
			--name mon \
			${DOCKERIMAGE} mon
		;;
	"mgr")
		docker run -d --net=host \
			--restart=always \
			-v /etc/ceph:/etc/ceph \
			-v /var/log/ceph/:/var/log/ceph/ \
			-v /var/lib/ceph/mgr:/var/lib/ceph/mgr \
			-v /var/lib/ceph/bootstrap-mds:/var/lib/ceph/bootstrap-mds \
			-v /var/lib/ceph/bootstrap-osd:/var/lib/ceph/bootstrap-osd \
			-v /var/lib/ceph/bootstrap-rbd:/var/lib/ceph/bootstrap-rbd \
			-v /var/lib/ceph/bootstrap-rgw:/var/lib/ceph/bootstrap-rgw \
			--name mgr \
			${DOCKERIMAGE} mgr
		;;
	"osds")
		shift
		for DEV in $*
		do
			if [ "$DEV" == "osdp" ]
			then
				OSDNAME=osdp
				docker run -d --net=host \
					--pid=host \
					--restart=always \
					-v /etc/ceph/:/etc/ceph \
					-v /var/log/ceph/:/var/log/ceph/ \
					-v /var/lib/ceph/bootstrap-mds:/var/lib/ceph/bootstrap-mds \
					-v /var/lib/ceph/bootstrap-osd:/var/lib/ceph/bootstrap-osd \
					-v /var/lib/ceph/bootstrap-rbd:/var/lib/ceph/bootstrap-rbd \
					-v /var/lib/ceph/bootstrap-rgw:/var/lib/ceph/bootstrap-rgw \
					-v /mnt/osd:/var/lib/ceph/osd \
					--name $OSDNAME \
					${DOCKERIMAGE} osd
			else
				OSDNAME=osd${DEV//\//-}
				docker run -d --net=host \
					--pid=host \
					--restart=always \
					--privileged=true \
					-v /etc/ceph:/etc/ceph \
					-v /var/log/ceph/:/var/log/ceph/ \
					-v /var/lib/ceph/bootstrap-mds:/var/lib/ceph/bootstrap-mds \
					-v /var/lib/ceph/bootstrap-osd:/var/lib/ceph/bootstrap-osd \
					-v /var/lib/ceph/bootstrap-rbd:/var/lib/ceph/bootstrap-rbd \
					-v /var/lib/ceph/bootstrap-rgw:/var/lib/ceph/bootstrap-rgw \
					-v /dev/:/dev/ \
					-e OSD_DEVICE=$DEV \
					--name $OSDNAME \
					${DOCKERIMAGE} osd
			fi
		done
		;;
	"osd-down")
		shift
		for DEV in $*
		do
			if [ "$DEV" == "osdp" ]
			then
				OSDNAME=osdp
			else
				OSDNAME=osd${DEV//\//-}
			fi
			echo "DOWN ${OSDNAME}"

			docker stop ${OSDNAME}
			docker rm ${OSDNAME}
		done
		;;
	"osd-zap")
		shift
		for DEV in $*
		do
			echo "CLEAN ${DEV}"
			if [ "$DEV" == "osdp" ]
			then
				sudo rm -rf /mnt/osd/*
			else
				docker run --rm --privileged=true \
					-v /dev/:/dev/ \
					-e OSD_DEVICE=$DEV \
					${DOCKERIMAGE} zap_device
			fi
		done
		;;
	"mds")
		shift
		PGNUM=$1
		[ -e ~/store/ceph/var/lib/ceph/mds ] \
		       	&& docker run -d --net=host \
				--restart=always \
				-v /etc/ceph:/etc/ceph \
				-v /var/log/ceph/:/var/log/ceph/ \
				-v /var/lib/ceph/mds:/var/lib/ceph/mds \
				-v /var/lib/ceph/bootstrap-mds:/var/lib/ceph/bootstrap-mds \
				-v /var/lib/ceph/bootstrap-osd:/var/lib/ceph/bootstrap-osd \
				-v /var/lib/ceph/bootstrap-rbd:/var/lib/ceph/bootstrap-rbd \
				-v /var/lib/ceph/bootstrap-rgw:/var/lib/ceph/bootstrap-rgw \
				--name mds \
				${DOCKERIMAGE} mds \
			|| docker run -d --net=host \
				--restart=always \
				-v /etc/ceph:/etc/ceph \
				-v /var/log/ceph/:/var/log/ceph/ \
				-v /var/lib/ceph/mds:/var/lib/ceph/mds \
				-v /var/lib/ceph/bootstrap-mds:/var/lib/ceph/bootstrap-mds \
				-v /var/lib/ceph/bootstrap-osd:/var/lib/ceph/bootstrap-osd \
				-v /var/lib/ceph/bootstrap-rbd:/var/lib/ceph/bootstrap-rbd \
				-v /var/lib/ceph/bootstrap-rgw:/var/lib/ceph/bootstrap-rgw \
				-e CEPHFS_CREATE=1 \
				-e CEPHFS_DATA_POOL_PG=$PGNUM \
				-e CEPHFS_METADATA_POOL_PG=$PGNUM \
				--name mds \
				${DOCKERIMAGE} mds
		;;
	"mdsmount")
		shift
		ACTIVEMDS=$1
		sudo apt install ceph-common${CEPHCOMMON_VERSION} autofs -y
		sudo apt-mark hold ceph-common
		echo $(sudo grep key /etc/ceph/ceph.client.admin.keyring  | cut -d= -f2-) | \
			sudo tee /etc/ceph/admin.secret
		sudo chmod 600 /etc/ceph/admin.secret
		cat /etc/auto.misc | grep "^mds" | grep ceph | grep ${ACTIVEMDS} || \
			echo "mds -fstype=ceph,noatime,nodiratime,name=admin,secretfile=/etc/ceph/admin.secret ${ACTIVEMDS}:/" | \
			sudo tee -a /etc/auto.misc
		cat /etc/auto.master | grep mnt | grep -F "/etc/auto.misc" || \
			echo "/mnt/misc /etc/auto.misc --timeout 0" | \
			sudo tee -a /etc/auto.master
		sudo service autofs restart
		;;
        "clean")
                docker stop mgr mon mds
                docker rm mgr mon mds
                ;;
        "cleanclean")
                $0 clean
		docker rmi ${DOCKERIMAGE}
                sudo rm -rf /etc/ceph /var/lib/ceph /var/log/ceph
                ;;
	"p-up")
		docker exec mgr ceph mgr module enable prometheus
		docker exec mgr ceph config set mgr mgr/prometheus/server_addr 127.0.0.1
		;;
	"p-down")
		docker exec mgr ceph mgr module disable prometheus
		;;
	"d-up")
		docker exec mgr ceph mgr module enable dashboard
		docker exec mgr ceph config set mgr mgr/dashboard/server_addr 127.0.0.1
		docker exec mgr ceph dashboard create-self-signed-cert
		docker exec mgr ceph dashboard set-login-credentials admin admin
		docker exec mgr ceph mgr services
		;;
	"d-down")
		docker exec mgr ceph mgr module disable dashboard
		;;
	*)
		echo $(basename $0) prepare
		echo $(basename $0) mon hostip network
		echo $(basename $0) mgr
		echo "$(basename $0) [osds/osds-down/osds-zap] osdp dev1 dev2 ..."
		echo $(basename $0) mds pgnum
		echo $(basename $0) mdsmount mdshost
		echo $(basename $0) clean
		echo $(basename $0) cleanclean
		echo $(basename $0) p-up ...
		echo $(basename $0) p-down
		echo $(basename $0) d-up
		echo $(basename $0) d-down
		;;
esac
